version: '3.9'
networks: 
  lan:
services:
  neo4j:
    image: neo4j:5.21.0-enterprise
    container_name: neo4j-service
    hostname: neo4j
    ports:
      - "8474:7474"
      - "8687:7687"
    environment:
      NEO4J_AUTH: "neo4j/testpassword"
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "eval"
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 1G
      NEO4J_server_default__listen__address: 0.0.0.0
      NEO4J_server_default__advertised__address: neo4j
      NEO4J_server_bolt_advertised__address: localhost:7687
      NEO4J_server_http_advertised__address: localhost:7474
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import
    networks:
      - lan

  jmeter:
    build: .
    container_name: jmeter-service
    volumes:
      - ./jmeter:/jmeter
    entrypoint: /bin/bash
    command: ["-c", "while true; do sleep 30; done;"]
    networks:
      - lan
